name: Deploy backend service to DigitalOcean

on:
  push:
    branches:
      - sprint-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests=true
    
      - name: Build Docker image for user service
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/user-service:latest ./user-service

      - name: Build Docker image for market service
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/market-service:latest ./market-service

      - name: Push Docker image to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push Docker image - user service
        run: docker push ${{secrets.DOCKER_USERNAME}}/user-service:latest

      - name: Push Docker image - market service
        run: docker push ${{secrets.DOCKER_USERNAME}}/market-service:latest

      - name: SCP Docker Compose and init.sql to PROD
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.PRODUCTION_HOST_IP}}
          username: ${{secrets.PRODUCTION_SERVER_USER}}
          key: ${{secrets.PRODUCTION_SERVER_SSH}}
          source: "./docker.compose.yaml"
          target: "/root/docker.compose.yaml"
          debug: true

      - name: SSH into PROD
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PRODUCTION_HOST_IP}}
          username: ${{secrets.PRODUCTION_SERVER_USER}}
          ssh_private_key: ${{secrets.PRODUCTION_SERVER_SSH}}
          script: |
            docker-compose -f /root/docker.compose.yml pull
            docker-compose -f /root/docker.compose.yml up -d
          
